### ISSUE TITLE
remove libaaio-0.3.1.tar.bz2 archive from sources

### ISSUE THREAD

**Issue by musger** [ComposersDesktop/CDP7#10]
I think this archive file is not needed in the sources, as its unpacked version lays next to it.

**Comment by fpesari** [comment]
The strange thing is that on my setup, libaaio-0.3.1.tar.bz2 builds just fine, while the unpacked directory doesn't.

**Comment by musger** [comment]
Hmm, are you getting an error message? Did you try a make clean in the non-tar.bz2
directory? 

* Fabio Pesari <notifications@github.com> [2020-04-13 11:32]:

**Comment by fpesari** [comment]
> Hmm, are you getting an error message? Did you try a make clean in the non-tar.bz2 directory? *

During `./configure` I get:

```
config.status: error: cannot find input file: `Makefile.in'
```

And it can't be fixed by using the usual `aclocal`, `autoconf`, `autoheader` and `automake` tricks.

`make clean` does not work since it doesn't even generate the Makefile in the first place...

**Comment by musger** [comment]
So it seems that Makefile.am is missing as well, from which automake
would create Makefile.in if I am not mistaken. 

* Fabio Pesari <notifications@github.com> [2020-04-13 18:00]:

**Comment by richarddobson** [comment]
I am working through all the recent messages.

It is appropriate to remove the unpacked libaaio directory to leave the 
tar.bz2 file (rather than the other way round). It was not really 
intended to be included. I will do this shortly. The libaaio archive has 
never been updated, and seems now to be effectively an orphan project. 
For anyone who needs an explanation for the use of libaaio here: it 
provides the interactive DOS functions for catching a key press that are 
not directly covered on unix systems including the Mac. It enables the 
programs to be built for all platforms without platform-specific code. 
It is used by only a few programs.

Richard Dobson

**Comment by jpffitch** [comment]
I removed the directory
